[options]
girs_dir = "../gir-files"
library = "PangoFc"
version = "1.0"
min_cfg_version = "1.44"
target_path = "."
work_mode = "normal"
generate_safety_asserts = true
deprecate_by_min_version = true
single_version_file = true

generate = [
    "PangoFc.FontMap",
]

manual = [
    "fontconfig.FcConfig",
]
