// This file was generated by gir (https://github.com/gtk-rs/gir)
// from gir-files (https://github.com/gtk-rs/gir-files)
// DO NOT EDIT

mod font_map;
pub use self::font_map::{FontMap, FontMapClass};

#[doc(hidden)]
pub mod traits {
}
